name: Django CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies and Flake8
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flake8
      run: |
        #flake8 article

    - name: Run tests
      run: python manage.py test

    - name: Build Docker image
      run: docker build -t kenkleven/g6_devops .

    - name: Login to Docker Hub (replace with your credentials)
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push kenkleven/g6_devops:latest

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}  # Store in GitHub Secrets
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB }}  # Store in GitHub Secrets
