name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Continue even if one step fails

    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Replace with your specific version

      - name: Install linters
        run: pip install flake8

      - name: Analyze code with Flake8
        run: flake8

      - name: Run unit tests (replace with your testing framework)
        run: |
          # Replace with your actual test command (e.g., pytest tests.py)
          python manage.py test

      - name: Build Docker image
        run: docker build -t your-username/your-project-name .

      - name: Login to Docker Hub (replace with your credentials)
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push your-username/your-project-name:latest

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Store in GitHub Secrets
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Store in GitHub Secrets
